### ISSUE TITLE
The "ocsigen" branch should be master

### ISSUE THREAD

**Issue by Armael** [ocsigen/camlp4-to-ppx#1]
Currently, to use camlp4-to-ppx on .eliom files, as advertised on http://ocsigen.org/eliom/5.0/manual/ppx-migration , one apparently has to go to the "ocsigen" branch of this repository. I do not think this is very intuitive; and it is not documented anywhere.

I think the simpler solution would be to have master be the current ocsigen branch.

**Comment by rand00** [comment]
1up from here - especially since git doesn't automatically pull all branches

**Comment by vasilisp** [comment]
I pushed the commits to our `master`. I am keeping an identical `ocsigen` branch because the Jane Street README points to it.
